### PR TITLE
[FEATURE] Add automatic debug settings

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Comment by oliverklee** [comment]
Blocked by #110.

**Comment by samtuke** [comment]
Ready for rebase

**Comment by oliverklee** [comment]
already done :-)

**Comment by oliverklee** [comment]
Oh, it looks like I need to whitelist something for PHPMD. Hold on …

**Comment by oliverklee** [comment]
Done. Hopefully, the build will be green now.

**Pull request merged**
