### PR TITLE
[BUGFIX] Fix MySQL with the new Trusty Travis images

### PR DESCRIPTION
**Pull request by oliverklee**
This fixes the build if Travis is using the new Trusty image.

### CODE REVIEW

**Comment by oliverklee** [comment]
Let's wait until I've fixed the issue for the rest-api package. I'll then update this PR accordingly.

**Comment by samtuke** [comment]
Ok!

**Comment by oliverklee** [comment]
Note to myself:
https://github.com/nazar-pc/CleverStyle-Framework/blob/master/.travis.yml

**Comment by oliverklee** [comment]
It's green now.

**Comment by oliverklee** [comment]
1. I've just checked: The Packagist GitHub web hook works fine again, and this revision now is available.
2. We still might get random MySQL errors on Travis every now and then. That is a different problem, though, than the problem solved in this PR (where builds would always have failed on Trusty).

**Pull request merged**
