### PR TITLE
[FEATURE] Add and import the database schema

### PR DESCRIPTION
**Pull request by oliverklee**
Now Travis import the database schema before each build.

The database schema has been taken from the development demo database
(but without the data).

### CODE REVIEW

**Comment by oliverklee** [comment]
@michield Should we use the SQL as taken from the dump (with the same formatting), or would you prefer it to be autoformatted it (so it is better readable=?

**Comment by samtuke** [comment]
The purpose of the SQL file is primarily for CI testing so in my view the dump is fine. phpList 3 contains the DB structure in array format in structure.php, and it is already planned to add SQL comments to the tables there for contextual documentation. After that is done, the re-dumped SQL here will have comments describing table purpose which will make it more informative.

**Comment by samtuke** [comment]
Please wait for Michiel's review also

**Comment by oliverklee** [comment]
This blocks the next coming PR. @michield Do you have time to take a look at this PR?

**Comment by samtuke** [comment]
I will merge this in the mean time; it can easily be replaced with another dataset in future.

**Pull request merged**
