### PR TITLE
[FEATURE] Application kernel and placeholder application bundle

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Comment by oliverklee** [comment]
Things that will come later (in separate commits):

- production server secret from environment variables
- move the configuration file for the application bundle to a Configuration/ directory

**Comment by oliverklee** [comment]
It looks like the system tests still don't run properly on Travis. I'll have a look at it.

**Comment by oliverklee** [comment]
This now should be green.

**Comment by oliverklee** [comment]
#121 should be merged before this one.

**Comment by oliverklee** [comment]
This PR is blocking the next steps for the REST API.

**Comment by samtuke** [comment]
Ready for rebase

**Comment by oliverklee** [comment]
Rebased and repushed.

**Pull request merged**
