### PR TITLE
[FEATURE] Add an AdministratorToken repository

### PR DESCRIPTION
**Pull request by oliverklee**
Also hook up the existing AdministratorToken model to Doctrine ORM.

### CODE REVIEW

**Comment by oliverklee** [comment]
This PR is blocked by #75. After that one is merged, I'll need to rebase this one here.

**Comment by samtuke** [comment]
#75 is ready

**Comment by oliverklee** [comment]
Rebased and repushed.

**Comment by samtuke** [comment]
It appears that currently the unit tests cannot be executed independently of Travis because the necessary env vars are only set in the .travis.yml file, and the phpunit.xml config file is not being loaded as part of bootstrap. Is this correct?

**Comment by oliverklee** [comment]
No, this is not correct. The integration tests (not the unit tests) indeed need the environment variables, though,

If you are running the tests from within PhpStorm, you can set the environment variables in the run configurations.

And on the command line, running the tests looks like this (on my machine):

`PHPLIST_DATABASE_NAME=phplist_dev PHPLIST_DATABASE_USER=phplist PHPLIST_DATABASE_PASSWORD=phplist vendor/bin/phpunit Tests/Integration/`

(You can also have these variables when running the unit tests. There, they are not needed, but also won't do any harm.)

**Comment by samtuke** [comment]
Thanks -- after setting the environment variables in the console they still aren't accessible to phpunit for the integration tests (var_dumping getenv('PHPLIST_DATABASE_PASSWORD') also returns false). However Travis tests pass so this must be working in other environments and I will approve..

**Comment by samtuke** [comment]
Requires rebase

**Comment by oliverklee** [comment]
On the console, you need to either pass the environment variables in the same line as the phpunit call, or you'll need to export them.

**Comment by oliverklee** [comment]
Rebased and repushed.

**Comment by samtuke** [comment]
I believe a stray semicolon was the cause. Test passes; now merging.

**Pull request merged**
