### PR TITLE
[CLEANUP] Use environment variables for the DB credentials

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Comment by oliverklee** [comment]
I'm not quite sure about the syntax (both of the .travis.yml as well as the usage of environment variables) and will appreciate a critical pair of eyes!

**Comment by samtuke** [comment]
The best way to check the syntax is to see if travis will run it, it seems to me. I'm not a Travis config expert, so either we merge this and take the risk or wait for Michiel to review. I vote for the first option. Any risks I've overlooked?

**Comment by oliverklee** [comment]
Well, it's green on Travis (we can see this without merging). But please wait, I'll read up on YAML syntax first to make sure I really understand what I'm doing here.

**Comment by oliverklee** [comment]
According to https://docs.travis-ci.com/user/environment-variables/ , this syntax is correct.

**Pull request merged**
